# Generated by Django 2.2 on 2019-05-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('birth', models.CharField(max_length=250)),
                ('passport', models.CharField(max_length=250)),
                ('issue', models.CharField(max_length=250)),
                ('expiry', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('music', models.CharField(max_length=250)),
                ('file', models.CharField(max_length=250)),
            ],
        ),
    ]
